version: 2.1

orbs:
  node: circleci/node@4.7.0

defaults: &defaults
  docker:
    - image: cimg/node:16.15.0

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          command: yarn lint

workflows:
  validate:
    jobs:
      - dependencies

      - lint:
          requires: [dependencies]
