name: PR Name Lint - Conventional Commit
on:
  pull_request:
    types: ['opened', 'edited', 'reopened']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      env:
        COMMITLINT_VERSION: $(node -pe "require('./package.json')['devDependencies']['@commitlint/config-conventional']")
      run: npm install @commitlint/config-conventional@$COMMITLINT_VERSION
    - uses: JulienKode/pull-request-name-linter-action@v0.5.0
